# This is a basic workflow

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: action/checkout@v2

    - name: Run a one-line scripts
      run: echo Hello, world!

    - name: Run a  multi-line scripts
      run:
        echo Add other action to build,
        echo test, and deploy your project.
